### tags
GET http://{{base_url}}/tags?token={{token}}

### query tags
GET http://{{base_url}}/tags?token={{token}}&name=24h&tate=1&page=1

### add tag
POST http://{{base_url}}/tags?token={{token}}&name=news&state=1&created_by=guanwei

### edit tag
PUT http://{{base_url}}/tags/1?token={{token}}&name=bad boy&state=0&modified_by=doudou

### delete tag
DELETE http://{{base_url}}/tags/1?token={{token}}

### articles
GET http://{{base_url}}/articles?token={{token}}

### article
GET http://{{base_url}}/articles/0?token={{token}}

### add article
POST http://{{base_url}}/articles?token={{token}}&title=a best dog robot&desc=a from China make best world dog robot&content=2020年02月24日 China release a new message, China make a best world robot! this is a dog robot.&created_by=guanwei&state=0&tag_id=1

### edit article
PUT http://{{base_url}}/articles/1?token={{token}}&title=a best dog robot!&modified_by=doudou&tag_id=4

### delete article
DELETE http://{{base_url}}/articles/2?token={{token}}

### get auth
GET http://{{host}}:{{port}}/auth?username=guanwei&password=gw666

###

